Crux to Firestore
avisi-apps/atlassian-connect-crux pull request #9
Opened 2021-02-17 16:14 UTC by fatihict

Resolves: ATOP-123

2021-02-17 16:18 UTC, fatihict commented
This PR will be merged to the branch `epic/firestore` and afterwards I will create a new library called `atlassian-connect-firestore`.

2021-02-17 16:27 UTC, TimovanderKamp approved these changes

2021-02-17 16:36 UTC, mitchelkuijpers requested changes

2021-02-17 16:36 UTC, mitchelkuijpers commented on .nrepl-port
> +44131
gitignore

2021-02-17 16:36 UTC, mitchelkuijpers commented on firebase.json
> +    "hosting": {
Gebruik je hosting? anders kan die weg

2021-02-17 16:36 UTC, mitchelkuijpers commented on firebase.json
> +    "functions": {
Gebruik je functions? anders kan dit weg dan start ie die ook niet meer op

2021-02-17 16:36 UTC, mitchelkuijpers commented on firebase.json
> +    "predeploy": "yarn shadow-cljs release functions && mkdir -p public"
Ah ik zou deze file even wat wat meer opschonen

2021-02-17 16:36 UTC, mitchelkuijpers commented on package.json
> +    "dev-firebase": "yarn firebase emulators:start --inspect-functions"
--inspect-functions heb je niet nodig ik zou alleen de firestore en de ui opstarten

2021-02-17 16:36 UTC, mitchelkuijpers commented on test/fixtures/firestore_fixtures.clj
> +(defn with-test-firestore [f] (mount/start-with {#'avisi.atlassian.connect.firestore/service service}) (f))
Ik zou liever zien dat we firestore in de env stoppen en dit dan kunnen mocken door dit mee te geven

2021-02-17 16:36 UTC, mitchelkuijpers commented on src/avisi/atlassian/connect/firestore.clj
> +       :new-host lifecycle-payload})))
Ik zou hier de payload omzetten naar hetzelfde format wat er nu is in de numbered-headings-cloud en edit-custom-field-values-cloud

2021-02-17 16:36 UTC, mitchelkuijpers commented on src/avisi/atlassian/connect/firestore.clj
> +        (string/starts-with? s ":")
Ik vind de keywords opslaan zoals: `:foo.bar/foo` persoonlijk niet echt mooi, lijkt me ook erg lastig als je een keer iets wilt doen met de data in iets anders dan Clojure

2021-02-17 16:36 UTC, mitchelkuijpers commented on src/avisi/atlassian/connect/firestore.clj
> +    {::document-path (format "hosts/%s" (host-client-key document))
Ik zag in de andere firstore api's dat ze hier een vector van maken dus: `[hosts (host-client-key document)]` dat vond ik persoonlijk wat mooier dan strings

2021-02-18 10:12 UTC, MareinK-Avisi approved these changes

2021-02-18 15:49 UTC, MareinK-Avisi approved these changes

2021-02-23 10:38 UTC, mitchelkuijpers approved these changes

2021-02-23 10:38 UTC, mitchelkuijpers commented on .firebaserc
> +    "default": "atlassian-connect"
Heet het project `atlassian-connect`? Ik zou dit even fixen naar bijv: `ecfv-dev` die kon ik nu vinden in firebase

2021-02-23 12:56 UTC, merged